namespace JSuite.Mapping.Parser.Parsing.Generic
{
    public interface IParserRuleConfigurator<TToken, TRule>
    {
        IParserRuleTokenItemConfigurator<TToken, TRule> WithT(TToken tokenType);

        IParserRuleRuleItemConfigurator<TToken, TRule> WithR(TRule ruleType);
    }

    public interface IParserRuleContinuationConfigurator<TToken, TRule>
    {
        IParserRuleTokenItemConfigurator<TToken, TRule> ThenT(TToken tokenType);

        IParserRuleRuleItemConfigurator<TToken, TRule> ThenR(TRule ruleType);
    }

    public interface IParserRuleItemConfigurator<TToken, TRule>
    {
        IParserRuleContinuationConfigurator<TToken, TRule> Once();
        IParserRuleContinuationConfigurator<TToken, TRule> AtMostOnce();
        IParserRuleContinuationConfigurator<TToken, TRule> AtLeastOnce();
        IParserRuleContinuationConfigurator<TToken, TRule> ZeroOrMore();
    }

    public interface IParserRuleTokenItemConfigurator<TToken, TRule> : IParserRuleItemConfigurator<TToken, TRule>
    {
        /// <summary>
        /// Configures this token to be matched but included in the returned parse tree.
        /// </summary>
        /// <returns>Itself.</returns>
        IParserRuleTokenItemConfigurator<TToken, TRule> Exclude();
    }

    public interface IParserRuleRuleItemConfigurator<TToken, TRule> : IParserRuleItemConfigurator<TToken, TRule>
    {
        /// <summary>
        /// Hoist the content generated by this rule item by one level.
        /// </summary>
        /// <returns>Itself.</returns>
        IParserRuleRuleItemConfigurator<TToken, TRule> Hoist();
    }
}